### ISSUE TITLE
NoMethodError: github.rb:90:in `register_hook'

### ISSUE THREAD

**Issue by matevz** [farend/scm-creator#12]
I'm getting the following error when importing existing github repository:

```
NoMethodError (undefined method `[]' for nil:NilClass):
  plugins/redmine_scm/app/models/repository/github.rb:90:in `register_hook'
  app/controllers/repositories_controller.rb:46:in `create'
  plugins/redmine_scm/lib/scm_repositories_controller_patch.rb:70:in `create_with_scm'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

I'm not using any API keys, but only public access. github section in scm.yml is only:
```
  github:
    path: /opt/redmine/github
```

This is on Redmine 3.4.6 and the latest master branch of scm-creator.

**Comment by matevz** [comment]
Hi.
It turns out the problem was in scm.yml. When I added

```
api:
  register_hook: false
```


The error was gone.

**Comment by ishikawa999** [comment]
Thank you for sharing the solution. 😄
