### ISSUE TITLE
Repository not removed from disk when deleting it

### ISSUE THREAD

**Issue by matevz** [farend/scm-creator#13]
When deleting github repository, the folder is not removed from the disk. If the repository is then re-imported, the cloning consequently fails.

**Comment by ishikawa999** [comment]
@matevz 
Thank you for sharing the problem.
I'm sorry, I could not reproduce the problem in my environment.

Could you confirm the following points to solve the problem?

* Do you use the latest program? (I fixed the function to delete repository file by updating 16 days ago)
* Have you checked yes when deleting the repository?
<kbd><img width="937" alt="confirmation" src="https://user-images.githubusercontent.com/14245262/47056844-3caf8d80-d1f9-11e8-9d30-90ae2e172040.png"></kbd>
* When deleting the repository Has the error message been output to the log file?
If a message such as "Failed to delete repository on file system: ~~~" is output to the production.log file, you may see the reason why deleting the repository does not work by looking at the message.

Thank you.

**Comment by matevz** [comment]
I found something in the log:
```
Failed to delete repository on file system: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/opt/redmine/git-repos/test3.0.git" (
parent directory mode 40777)
```

**Comment by ishikawa999** [comment]
@matevz 

Thank you for sharing the error message.
The repository removal method checks the permissions of the parent directory(git-repos) for security.
Deletion is not successful if all users can write the parent directory(git-repos).
Try changing the permissions of the parent directory(git-repos).

```
sudo chmod o+t -R git-repos
```
or 
Change as written in https://github.com/farend/scm-creator/blob/master/README.md#1-creating-root-directory

This blog was helpful: https://jitendrapmfs.wordpress.com/2015/01/29/argumenterror-parent-directory-is-world-writablefileutilsremove_entry_secure-does-not-work/

**Comment by matevz** [comment]
Hm.. so the `git-repos` directory in our case is a nfs-mounted network drive from a machine which also runs apache for checking out git repos. This allows us to still use git, if something is wrong with redmine&rails machine and backup it separately from the redmine. So the folder must be writeable by at least two users - the redmine one for creating/deleting the repo and the apache one for actually pushing to the repo. How this is done now is simply by chmoding `git-repos` to 777.

Is there an option to disable this security check or maybe only check whether the parent directory is owned by the redmine user and not root? I guess the "security" refers not to do `rm -rf /`, right?

**Comment by ishikawa999** [comment]
@matevz 
I'm sorry I got a late reply.

Deletion fails due to the mechanism to avoid security holes as described in the document below.
https://apidock.com/ruby/FileUtils/remove_entry_secure
Therefore, I do not want to change the current deletion mechanism.

Could you rewrite program files directly?
If you change "FileUtils.remove_entry_secure(path, false)" to "FileUtils.rm_r(path)" as shown below, you should be able to delete the repository in your environment as well.

If FileUtils.rm_r(path) does not work, it may be better to use FileUtils.rm_rf(path).

change file: redmine/plugins/redmine_scm/lib/creator/scm_creator.rb
```diff
diff --git a/lib/creator/scm_creator.rb b/lib/creator/scm_creator.rb
index a9ff196..33ed57f 100644
--- a/lib/creator/scm_creator.rb
+++ b/lib/creator/scm_creator.rb
@@ -132,7 +132,7 @@ class SCMCreator
         # removes repository
         def delete_repository(path)
             # See: http://www.ruby-doc.org/stdlib-1.9.3/libdoc/fileutils/rdoc/FileUtils.html#method-c-remove_entry_secure
-            FileUtils.remove_entry_secure(path, false)
+            FileUtils.rm_r(path)
             true
         rescue => error
             Rails.logger.error "Failed to delete repository on file system: #{error.message}"

```

**Comment by ishikawa999** [comment]
In redmine 4.0, the error message was not displayed even if repository deletion failed, so it was fixed.
4e59471f4068af967168ade8d3941c1fee4aadb1

**Comment by matevz** [comment]
Crap, files created by git on the other machine are owned by `www-data` and have `600` permissions, so removing them by the redmine user won't work anyway... I will need to think about this.
The issue can be closed, since it's a sysadmin issue now and not redmine-related anymore. Thanks.

**Comment by ishikawa999** [comment]
> Crap, files created by git on the other machine are owned by `www-data` and have `600` permissions, so removing them by the redmine user won't work anyway... I will need to think about this.
> The issue can be closed, since it's a sysadmin issue now and not redmine-related anymore. Thanks.

I'm sorry I couldn't help you.
I will close this issue.
