### ISSUE TITLE
Apache2 conf.d no longer exists in 2.4

### ISSUE THREAD

**Issue by speedy32129** [farend/scm-creator#17]
In apache2 the conf.d is no longer there so what file does the info in the big block into as it states in the install for "Then add the following Location directives to your apache configuration (for example in /etc/APACHE_DIR/conf.d/):" go?  

I'd love to help out as I loved this plugin!!!

**Comment by ishikawa999** [comment]
Which OS do you use?
I think that the position where the configuration file is added changes with OS.

Redmine documentation is outdated, so I recommend looking for more useful information on the Internet.
Sorry, I may not be able to do much help because I'm not familiar with apache2.

**Comment by speedy32129** [comment]
It's Debian.  I use a TurnkeyLinux Redmine appliance.  They're pretty cool because I can rollback changes and things.  Well I've answer my own question tonight and just so everyone knows the conf.d in TurnkeyLinux Redmine 15.1 appliance is now moved into /etc/apache2/conf-available/redmine_webaccess.conf.  I'm going to make my changes there to complete the install.

**Comment by ishikawa999** [comment]
Thank you for sharing the solution. This issue is closed.
