### ISSUE TITLE
Issue with Redmine 5.0.2

### ISSUE THREAD

**Issue by Sandhyarani31** [farend/scm-creator#20]
Hello,

I am trying to use this plugin for redmine 5.0.2, plugin migrate is throwing some error

LoadError: cannot load such file -- creator/scm_creator
/usr1/data/redmine/plugins/redmine_scm/init.rb:8:in `<top (required)>'
/usr1/data/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/usr1/data/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/usr1/data/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/usr1/data/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/usr1/data/redmine/config/environment.rb:16:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment

Can you please help me to resolve this issue. 
Thank you

**Comment by ishikawa999** [comment]
Sorry, I am not currently using this plugin and cannot maintain it.
I apologize for not being able to help you.
I will archive this repository.
